### ISSUE TITLE
Minor errors during server startup

### ISSUE THREAD

**Issue by Lurmey** [kwpugh/easy_steel#1]
[latest.log](https://github.com/kwpugh/easy_steel/files/3777066/latest.log)

As the title says, just a couple of errors showing up during server startup. These errors are not fatal but I thought it best to report them anyways. Uploaded log file but I'll highlight the errors below too.

Lines 70-93
`[28Oct2019 00:04:28.055] [Server-Worker-1/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read block tag list forge:ores/copper from forge:tags/blocks/ores/copper.json in data pack EasySteel-1.14.4-1.0.45.jar
com.google.gson.JsonParseException: Unknown value 'easy_steel:copper_powder'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_221]
[28Oct2019 00:04:28.091] [Server-Worker-1/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read block tag list forge:ores/tin from forge:tags/blocks/ores/tin.json in data pack EasySteel-1.14.4-1.0.45.jar
com.google.gson.JsonParseException: Unknown value 'easy_steel:tin_powder'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_221]`

**Comment by kwpugh** [comment]
Thanks, I will take a look.

**Comment by kwpugh** [comment]
Unnecessary forge tags removed in latest release.
